<a href="https://colab.research.google.com/github/ArindamBanerji/feature-eng-eda-recipes/blob/main/tf_keras1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.17563733,  0.01258755, -0.17299312, -0.11426884, -0.13803641,
        -0.11894275,  0.37921748,  0.7759262 , -0.80704695, -0.49330786]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.11475627, 0.09749106, 0.08097821, 0.085876  , 0.083859  ,
        0.08547556, 0.14066634, 0.20915997, 0.04295385, 0.05878374]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.4595249

In [10]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)

In [11]:
opt_rmsprop = tf.keras.optimizers.RMSprop(learning_rate=0.001)

In [12]:
# Create a copy of the test model (with freshly initialized weights).
model_rms = tf.keras.models.clone_model(model)

In [13]:
model.compile(optimizer=opt,
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model_rms.compile(optimizer=opt_rmsprop,
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2943 - accuracy: 0.9148
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1443 - accuracy: 0.9571
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1078 - accuracy: 0.9673
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0879 - accuracy: 0.9730
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0764 - accuracy: 0.9756
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0650 - accuracy: 0.9792
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0592 - accuracy: 0.9810
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0556 - accuracy: 0.9821
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0499 - accuracy: 0.9834
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.045

In [16]:
model_rms.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2946 - accuracy: 0.9140
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1539 - accuracy: 0.9562
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1241 - accuracy: 0.9651
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1121 - accuracy: 0.9682
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1029 - accuracy: 0.9719
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0931 - accuracy: 0.9748
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0913 - accuracy: 0.9760
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0845 - accuracy: 0.9783
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0812 - accuracy: 0.9787
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.079

In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0706 - accuracy: 0.9778 - 492ms/epoch - 2ms/step


[0.07060760259628296, 0.9778000116348267]

In [18]:
model_rms.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.1049 - accuracy: 0.9769 - 395ms/epoch - 1ms/step


[0.10492995381355286, 0.9768999814987183]

In [19]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.6794346e-10, 1.5458491e-10, 3.9979842e-09, 1.7408529e-05,
        2.4998597e-14, 1.2788077e-09, 4.0764995e-18, 9.9998200e-01,
        2.0259290e-09, 5.7485386e-07],
       [4.4404858e-11, 9.5545456e-06, 9.9998951e-01, 4.7612846e-07,
        4.2687317e-17, 2.8902457e-07, 1.6765932e-09, 9.2211956e-16,
        9.2010815e-08, 2.3843442e-15],
       [4.9980201e-07, 9.9875283e-01, 1.1488970e-05, 1.0194839e-05,
        3.5307512e-05, 1.6805848e-07, 4.1403191e-06, 9.7536872e-04,
        2.0983156e-04, 2.4340804e-07],
       [9.9999797e-01, 1.0684471e-14, 1.8653229e-07, 2.1970124e-10,
        3.0062611e-10, 5.9628860e-08, 1.5695698e-06, 3.6052672e-08,
        3.6485008e-09, 6.7322773e-08],
       [1.0199341e-06, 4.5447354e-11, 8.1257738e-08, 4.2343497e-11,
        9.9968147e-01, 6.6116495e-09, 4.2920087e-07, 7.5811913e-05,
        1.2762678e-08, 2.4113410e-04]], dtype=float32)>

## Image classification example

In [21]:
# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.9.2


In [22]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step
