<a href="https://colab.research.google.com/github/ArindamBanerji/feature-eng-eda-recipes/blob/main/tf_keras1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.58935064,  0.3406536 , -0.21077949, -0.08009169, -0.36762384,
         0.04286391, -0.56144327,  0.24851528, -0.7850466 ,  0.6196739 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.05780018, 0.14649571, 0.08439963, 0.09618283, 0.07214794,
        0.10876683, 0.05943595, 0.13360101, 0.0475269 , 0.19364303]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.2185488

In [48]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)

In [49]:
opt_rmsprop = tf.keras.optimizers.RMSprop(learning_rate=0.001)

In [50]:
# Create a copy of the test model (with freshly initialized weights).
model_rms = tf.keras.models.clone_model(model)

In [51]:
model.compile(optimizer=opt,
              loss=loss_fn,
              metrics=['accuracy'])

In [52]:
model_rms.compile(optimizer=opt_rmsprop,
              loss=loss_fn,
              metrics=['accuracy'])

In [53]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5772 - accuracy: 0.8781
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5162 - accuracy: 0.8732
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5182 - accuracy: 0.8712
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4983 - accuracy: 0.8692
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5031 - accuracy: 0.8685
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5038 - accuracy: 0.8696
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4889 - accuracy: 0.8710
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4825 - accuracy: 0.8726
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4718 - accuracy: 0.8761
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.481

In [54]:
model_rms.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2894 - accuracy: 0.9156
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1575 - accuracy: 0.9552
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1264 - accuracy: 0.9646
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1125 - accuracy: 0.9693
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1038 - accuracy: 0.9721
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0974 - accuracy: 0.9743
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0888 - accuracy: 0.9760
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0848 - accuracy: 0.9775
Epoch 9/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0832 - accuracy: 0.9789
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.080

In [55]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 1.5596 - accuracy: 0.8949 - 587ms/epoch - 2ms/step


[1.5595730543136597, 0.8949000239372253]

In [56]:
model_rms.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.1019 - accuracy: 0.9781 - 580ms/epoch - 2ms/step


[0.10185010731220245, 0.9781000018119812]

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.87494886e-09, 6.52336496e-09, 1.39833162e-07, 4.35253489e-04,
        3.97832739e-11, 5.89387774e-08, 2.64788110e-13, 9.99561489e-01,
        1.03311481e-06, 1.96992346e-06],
       [3.56540641e-09, 1.99167152e-05, 9.99977589e-01, 2.01089938e-06,
        2.18160979e-17, 3.18006776e-08, 7.88567212e-10, 2.32197204e-12,
        4.72893589e-07, 7.12313102e-14],
       [2.40834811e-06, 9.97580290e-01, 1.47854571e-05, 6.05425748e-06,
        3.00110041e-05, 3.33244179e-06, 8.81806227e-06, 2.20567337e-03,
        1.48235558e-04, 4.43536408e-07],
       [9.96232927e-01, 3.07270689e-08, 3.89282446e-04, 1.03128241e-06,
        4.80578892e-05, 6.64044046e-06, 2.77549634e-03, 1.69343020e-05,
        2.05996770e-07, 5.29411249e-04],
       [1.34828849e-06, 2.41985614e-08, 3.26339978e-05, 7.99213922e-07,
        9.95734155e-01, 1.14435764e-07, 2.46401646e-06, 3.64544612e-05,
        3.06392781e-06, 4.18891991e-03]], dtype=float32)>

## Image classification example

In [19]:
# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.9.2
